### ISSUE TITLE
post requests handling not working

### ISSUE THREAD

**Issue by m-adil** [maciejsikora/node-express-babel-boilerplate#2]
In `routes.js`, I tried creating a new POST based route handling in this way:

    app.post('/test', (req, res, next) => {
        console.log('test');
	    console.log(req.body);
	    res.end();
    });

But unfortunately it's not working whereas multiple get requests are working perfectly fine. @maciejsikora Can you please point out if I'm making any mistake?

**Comment by m-adil** [comment]
I think it was because of [body-parser](https://github.com/expressjs/body-parser), It's working fine now after installation of body-parser.

**Comment by maciejsikora** [comment]
I am glad that You successfully solve the problem

**Comment by m-adil** [comment]
Thanks. I really liked that boilerplate and gonna use this setup for my new app. 👍
